spring.application.name=BreakoutDrop

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/breakout_drop_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_db}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:XdZigg!?176}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
